# Navbar Menus
[[nav]]
    name    = "about"
    url     = "about"
    weight  = 2
    identifier = "about"

[[nav]]
    name    = "products"
    url     = "products"
    weight  = 3
    identifier = "products"

[[nav]]
    name    = "blog"
    url     = "blog"
    weight  = 4
    identifier = "blog"

[[nav]]
    name    = "login"
    url     = "https://app.legalx.ai/login"
    weight  = 4
    identifier = "login"

# Footer Quick links Menu
[[quicklink]]
    name    = "about"
    url     = "about"
    weight  = 2

[[quicklink]]
    name    = "products"
    url     = "products"
    weight  = 3

[[quicklink]]
    name    = "blog"
    url     = "blog"
    weight  = 4

[[quicklink]]
    name    = "contact"
    url     = "contact"
    weight  = 5

[[quicklink]]
    name    = "terms"
    url     = "terms"
    weight  = 6

[[quicklink]]
    name    = "privacy"
    url     = "privacy"
    weight  = 7
