baseURL = "http://localhost:1313/"
languageCode = "en"
title = "LegalX"
theme = "navigator-hugo"
logo = "images/logo.png"
dateFormat = "2 January 2006"

enableRobotsTXT = false
googleAnalytics = ""
enableGitInfo = false
pygmentsCodeFences = false
menufixed = true

# Multilangues setup
defaultContentLanguageInSubdir = false
defaultContentLanguage = "en"
hasCJKLanguage = true
