[en]
  weight = 1
  languageCode = "en"
  languageName = "EN"
  title = "LegalX"
  logo = "images/logo.png"
  dateFormat = "2 January 2006"

  # Hero Section
  [en.params.hero]
    enable = true
    heading = "Execute your projects, professionally."
    description = "LegalX empowers your team to collaborate real-time and reproduce high-value workflows, with tight access control, document management and insanely fast search capabilities."

  # Contact Section
  [en.params.contact]
    enable  = true
    topTitle= ""
    title   = ""
    subtitle= "Schedule a product demonstration with us"
    address = "14-16 Gilman's Bazaar, Central, Hong Kong"
    phone   = "+852 2833 6981"

  # Blog Section On Homepage
  [en.params.blog]
    enable  = true
    title   = "Blog"

[zh-Hant]
  weight = 2
  languageCode = "zh-Hant"
  languageName = "繁"
  title = "LegalX"
  logo = "images/logo.png"
  dateFormat = "2 January 2006"

  # Hero Section
  [zh-Hant.params.hero]
    enable = true
    heading = "讓團隊擁有頂尖的項目執行能力"
    description = "法智科技爲客戶提供先進的項目管理技術促進綜合雲端平台即時協作，把工作流程自動化并爲專業團隊和企業團隊引用人工智能。"

  # Contact Section
  [zh-Hant.params.contact]
    enable  = true
    topTitle= ""
    title   = ""
    subtitle= "免費預約産品演示"
    address = "中國香港中環機利文新街14-16號1-2樓"
    phone   = "+852 2833 6981"

  # Blog Section On Homepage
  [zh-Hant.params.blog]
    enable  = true
    title   = "博客"

[zh-Hans]
  weight = 3
  languageCode = "zh-Hans"
  languageName = "简"
  title = "LegalX"
  logo = "images/logo.png"
  dateFormat = "2 January 2006"

  # Hero Section
  [zh-Hans.params.hero]
    enable = true
    heading = "让团队拥有顶尖的项目执行能力"
    description = "法智科技为客户提供先进的项目管理技术促进综合云端平台即时协作，把工作流程自动化并为专业团队和企业团队引用人工智能。"

  # Contact Section
  [zh-Hans.params.contact]
    enable  = true
    topTitle= ""
    title   = ""
    subtitle= "免费预约产品演示"
    address = "中国香港中环机利文新街14-16号1-2楼"
    phone   = "+852 2833 6981"

  # Blog Section On Homepage
  [zh-Hans.params.blog]
    enable  = true
    title   = "博客"
